# Isla configuration for sail-x86-from-acl2 model (x86-64 mode)

pc = "rip"

comment_prefixes = ["#", "//"]

default_sizeof = 1

[[toolchain]]
name = "default"
assembler = "as --64"
objdump = "objdump"
linker = "ld"
nm = "nm"

[mmu]
page_table_base = "0x300000"
page_size = "4096"
s2_page_table_base = "0x300000"
s2_page_size = "4096"

[threads]
base = "0x400000"
top = "0x500000"
stride = "0x10000"

[symbolic_addrs]
base = "0x600000"
top = "0x700000"
stride = "0x10"

[registers.defaults]
app_view = "true"
marking_view = "false"
log_register_writes = "false"
ms_reg = "false"
fault_reg = "false"
rflags = "{ bits = 0x00000002 }"
