#!/bin/bash
# Run symbolic equivalence verification between sail-x86 and sail-x86-from-acl2.
# Generates Isla traces and compares them using Z3.
#
# Usage:
#   ./run_equiv.sh                    # verify all instructions
#   ./run_equiv.sh add mov shl        # verify specific instructions
#
# Prerequisites:
#   - IR files generated by generate_ir.sh (in $IR_DIR or fallback paths)
#   - isla-execute-function binary built

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ISLA="${ISLA_DIR:-$HOME/isla}/target/release/isla-execute-function"
IR_DIR="${IR_DIR:-$SCRIPT_DIR/ir}"
TRACE_DIR="${TRACE_DIR:-/tmp/isla_traces}"
TIMEOUT="${TIMEOUT:-300}"

# Resolve IR files with fallback paths
resolve_ir() {
    local primary="$1"
    local fallback="$2"
    local label="$3"
    if [[ -f "$primary" ]]; then
        echo "$primary"
    elif [[ -f "$fallback" ]]; then
        echo >&2 "Note: using fallback IR for $label: $fallback"
        echo "$fallback"
    else
        echo >&2 "Error: $label IR file not found at:"
        echo >&2 "  $primary"
        echo >&2 "  $fallback"
        echo >&2 "Run generate_ir.sh first to produce the IR files."
        return 1
    fi
}

OURS_IR="${OURS_IR:-$(resolve_ir "$IR_DIR/sail_x86.ir" "/tmp/sail_x86_ours_v12.ir" "our model")}"
ACL2_IR="${ACL2_IR:-$(resolve_ir "$IR_DIR/acl2_x86.ir" "/tmp/acl2_x86_v6.ir" "ACL2 model")}"

OURS_CFG="$SCRIPT_DIR/x86_config_ours.toml"
ACL2_CFG="$SCRIPT_DIR/x86_config_acl2.toml"

# Instruction test function names
declare -A INSTRUCTIONS
INSTRUCTIONS[add]="isla_test_add_r64_imm32"
INSTRUCTIONS[mov]="isla_test_mov_r64_imm64"
INSTRUCTIONS[shl]="isla_test_shl_r64_imm8"

# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------

check_prerequisites() {
    local ok=true

    if [[ ! -x "$ISLA" ]]; then
        echo >&2 "Error: isla-execute-function not found at $ISLA"
        echo >&2 "Set ISLA_DIR to the isla repository root, or build it with:"
        echo >&2 "  cd ~/isla && cargo build --release --bin isla-execute-function"
        ok=false
    fi

    if [[ ! -f "$OURS_IR" ]]; then
        echo >&2 "Error: our model IR not found: $OURS_IR"
        ok=false
    fi

    if [[ ! -f "$ACL2_IR" ]]; then
        echo >&2 "Error: ACL2 model IR not found: $ACL2_IR"
        ok=false
    fi

    if [[ ! -f "$OURS_CFG" ]]; then
        echo >&2 "Error: our model config not found: $OURS_CFG"
        ok=false
    fi

    if [[ ! -f "$ACL2_CFG" ]]; then
        echo >&2 "Error: ACL2 model config not found: $ACL2_CFG"
        ok=false
    fi

    if ! command -v python3 &>/dev/null; then
        echo >&2 "Error: python3 not found in PATH"
        ok=false
    fi

    if [[ "$ok" != true ]]; then
        exit 1
    fi
}

# ---------------------------------------------------------------------------
# Trace generation
# ---------------------------------------------------------------------------

# Run isla-execute-function and return the output file path.
# Args: func_name ir_file cfg_file output_file
generate_traces() {
    local func_name="$1"
    local ir_file="$2"
    local cfg_file="$3"
    local output_file="$4"

    "$ISLA" "$func_name" \
        --arch "$ir_file" \
        --config "$cfg_file" \
        --traces -s --simplify-registers \
        --timeout "$TIMEOUT" \
        > "$output_file" 2>&1
}

# Count traces in an output file (heuristic: count "Trace " lines)
count_traces() {
    grep -c '^Trace ' "$1" 2>/dev/null || echo 0
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

check_prerequisites
mkdir -p "$TRACE_DIR"

# Determine which instructions to verify
if [[ $# -gt 0 ]]; then
    targets=("$@")
else
    targets=("${!INSTRUCTIONS[@]}")
fi

# Validate targets
for t in "${targets[@]}"; do
    if [[ -z "${INSTRUCTIONS[$t]+x}" ]]; then
        echo >&2 "Error: unknown instruction '$t'"
        echo >&2 "Available: ${!INSTRUCTIONS[*]}"
        exit 1
    fi
done

echo "=== Equivalence Verification ==="
echo "Our IR:   $OURS_IR"
echo "ACL2 IR:  $ACL2_IR"
echo "Traces:   $TRACE_DIR"
echo "Timeout:  ${TIMEOUT}s"
echo "Targets:  ${targets[*]}"
echo ""

# Results arrays
declare -a res_names=()
declare -a res_ours_traces=()
declare -a res_ours_times=()
declare -a res_acl2_traces=()
declare -a res_acl2_times=()
declare -a res_cmp_times=()
declare -a res_results=()

pass_count=0
fail_count=0
error_count=0

for insn in "${targets[@]}"; do
    func="${INSTRUCTIONS[$insn]}"
    ours_out="$TRACE_DIR/${insn}_ours.txt"
    acl2_out="$TRACE_DIR/${insn}_acl2.txt"

    echo "--- $insn ($func) ---"

    # Generate our model traces
    echo -n "  Our model...   "
    ours_start=$(date +%s%N)
    if generate_traces "$func" "$OURS_IR" "$OURS_CFG" "$ours_out"; then
        ours_end=$(date +%s%N)
        ours_ms=$(( (ours_end - ours_start) / 1000000 ))
        ours_tc=$(count_traces "$ours_out")
        echo "done (${ours_ms}ms, ${ours_tc} traces)"
    else
        ours_end=$(date +%s%N)
        ours_ms=$(( (ours_end - ours_start) / 1000000 ))
        ours_tc=0
        echo "FAILED (${ours_ms}ms)"
        echo "  See: $ours_out"
        res_names+=("$insn")
        res_ours_traces+=("ERR")
        res_ours_times+=("${ours_ms}ms")
        res_acl2_traces+=("-")
        res_acl2_times+=("-")
        res_cmp_times+=("-")
        res_results+=("ERROR")
        (( error_count++ ))
        continue
    fi

    # Generate ACL2 model traces
    echo -n "  ACL2 model...  "
    acl2_start=$(date +%s%N)
    if generate_traces "$func" "$ACL2_IR" "$ACL2_CFG" "$acl2_out"; then
        acl2_end=$(date +%s%N)
        acl2_ms=$(( (acl2_end - acl2_start) / 1000000 ))
        acl2_tc=$(count_traces "$acl2_out")
        echo "done (${acl2_ms}ms, ${acl2_tc} traces)"
    else
        acl2_end=$(date +%s%N)
        acl2_ms=$(( (acl2_end - acl2_start) / 1000000 ))
        acl2_tc=0
        echo "FAILED (${acl2_ms}ms)"
        echo "  See: $acl2_out"
        res_names+=("$insn")
        res_ours_traces+=("$ours_tc")
        res_ours_times+=("${ours_ms}ms")
        res_acl2_traces+=("ERR")
        res_acl2_times+=("${acl2_ms}ms")
        res_cmp_times+=("-")
        res_results+=("ERROR")
        (( error_count++ ))
        continue
    fi

    # Compare traces
    echo -n "  Comparing...   "
    cmp_start=$(date +%s%N)
    if python3 "$SCRIPT_DIR/compare_traces.py" "$ours_out" "$acl2_out"; then
        cmp_end=$(date +%s%N)
        cmp_ms=$(( (cmp_end - cmp_start) / 1000000 ))
        echo "PASS (${cmp_ms}ms)"
        result="PASS"
        (( pass_count++ ))
    else
        cmp_end=$(date +%s%N)
        cmp_ms=$(( (cmp_end - cmp_start) / 1000000 ))
        echo "FAIL (${cmp_ms}ms)"
        result="FAIL"
        (( fail_count++ ))
    fi

    res_names+=("$insn")
    res_ours_traces+=("$ours_tc")
    res_ours_times+=("${ours_ms}ms")
    res_acl2_traces+=("$acl2_tc")
    res_acl2_times+=("${acl2_ms}ms")
    res_cmp_times+=("${cmp_ms}ms")
    res_results+=("$result")

    echo ""
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo ""
echo "=== Summary ==="
printf "%-10s  %8s %10s  %8s %10s  %10s  %s\n" \
    "Insn" "Ours(#)" "Ours(t)" "ACL2(#)" "ACL2(t)" "Cmp(t)" "Result"
printf "%-10s  %8s %10s  %8s %10s  %10s  %s\n" \
    "----------" "--------" "----------" "--------" "----------" "----------" "------"

for i in "${!res_names[@]}"; do
    printf "%-10s  %8s %10s  %8s %10s  %10s  %s\n" \
        "${res_names[$i]}" \
        "${res_ours_traces[$i]}" "${res_ours_times[$i]}" \
        "${res_acl2_traces[$i]}" "${res_acl2_times[$i]}" \
        "${res_cmp_times[$i]}" \
        "${res_results[$i]}"
done

echo ""
echo "Pass: $pass_count  Fail: $fail_count  Error: $error_count  Total: ${#res_names[@]}"

if [[ $fail_count -gt 0 || $error_count -gt 0 ]]; then
    exit 1
fi
